South version bumped to 0.8.1 in order to fix innodb related bug in South.
This fixes:
......
    return self.run_migration(migration)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/opt/demovibes/demovibes/../demovibes/webview/migrations/0044_add_tag_history.py", line 67, in forwards
    db.alter_column('webview_song', 'platform_id', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['webview.SongPlatform'], null=True, blank=True))
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 397, in alter_column
    field.rel.to._meta.get_field(field.rel.field_name).column
  File "/usr/local/lib/python2.7/dist-packages/south/db/generic.py", line 150, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 34, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 86, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1005, "Can't create table 'demovibes.#sql-18c_51' (errno: 121)")